# site settings
title: Freinds of Dawsholm Park
subtitle: A Glasgow City community group
email: friends@dawsholmpark.co.uk
description: Looking after Glasgow's hidden jungle
baseurl: "/"
url: https://dawsholmpark.co.uk/
author:
street_address: Dawsholm Park
city: Glasgow
state: Scotland
zip_code: G20 0TF
country: United Kingdom
phone:

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
